// @generated by tools/generate_bindings.py; do not edit.
// Declarations derived from tblite 0.7.0, LGPL-3.0-or-later.
// See vendor/tblite-0.7.0/COPYING{,.LESSER} and NOTICE.md.
use std::ffi::{c_char, c_double, c_int, c_uint, c_void};
#[repr(C)]
pub struct _tblite_calculator {
    _private: [u8; 0],
}
pub type tblite_calculator = *mut _tblite_calculator;
#[repr(C)]
pub struct _tblite_container {
    _private: [u8; 0],
}
pub type tblite_container = *mut _tblite_container;
#[repr(C)]
pub struct _tblite_context {
    _private: [u8; 0],
}
pub type tblite_context = *mut _tblite_context;
#[repr(C)]
pub struct _tblite_double_dictionary {
    _private: [u8; 0],
}
pub type tblite_double_dictionary = *mut _tblite_double_dictionary;
#[repr(C)]
pub struct _tblite_error {
    _private: [u8; 0],
}
pub type tblite_error = *mut _tblite_error;
#[repr(C)]
pub struct _tblite_param {
    _private: [u8; 0],
}
pub type tblite_param = *mut _tblite_param;
#[repr(C)]
pub struct _tblite_result {
    _private: [u8; 0],
}
pub type tblite_result = *mut _tblite_result;
#[repr(C)]
pub struct _tblite_structure {
    _private: [u8; 0],
}
pub type tblite_structure = *mut _tblite_structure;
#[repr(C)]
pub struct _tblite_table {
    _private: [u8; 0],
}
pub type tblite_table = *mut _tblite_table;
#[repr(C)]
pub struct _tblite_array {
    _private: [u8; 0],
}
pub type tblite_array = *mut _tblite_array;
pub type tblite_guess = c_uint;
pub const TBLITE_GUESS_SAD: tblite_guess = 0;
pub const TBLITE_GUESS_EEQ: tblite_guess = 1;
pub const TBLITE_GUESS_EEQBC: tblite_guess = 2;
pub type tblite_mixer = c_uint;
pub const TBLITE_MIXER_BROYDEN: tblite_mixer = 1;
pub type tblite_ref_solvation_state = c_uint;
pub const tblite_state_gsolv: tblite_ref_solvation_state = 1;
pub const tblite_state_bar1mol: tblite_ref_solvation_state = 2;
pub const tblite_state_reference: tblite_ref_solvation_state = 3;
pub type tblite_born_kernel = c_uint;
pub const tblite_born_still: tblite_born_kernel = 1;
pub const tblite_born_p16: tblite_born_kernel = 2;
pub type tblite_solvation_param = c_uint;
pub const tblite_solvation_gbe: tblite_solvation_param = 10;
pub const tblite_solvation_alpb_gfn1: tblite_solvation_param = 11;
pub const tblite_solvation_alpb_gfn2: tblite_solvation_param = 12;
pub const tblite_solvation_gb: tblite_solvation_param = 20;
pub const tblite_solvation_gbsa_gfn1: tblite_solvation_param = 21;
pub const tblite_solvation_gbsa_gfn2: tblite_solvation_param = 22;
pub const tblite_solvation_ddcosmo: tblite_solvation_param = 100;
pub const tblite_solvation_ddcpcm: tblite_solvation_param = 101;
pub const tblite_solvation_ddpcm: tblite_solvation_param = 200;
pub type tblite_table_value_type = c_uint;
pub const TBLITE_TABLE_VALUE_TYPE_NONE: tblite_table_value_type = 0;
pub const TBLITE_TABLE_VALUE_TYPE_BOOL: tblite_table_value_type = 1;
pub const TBLITE_TABLE_VALUE_TYPE_INT: tblite_table_value_type = 2;
pub const TBLITE_TABLE_VALUE_TYPE_DOUBLE: tblite_table_value_type = 3;
pub const TBLITE_TABLE_VALUE_TYPE_CHAR: tblite_table_value_type = 4;
pub const TBLITE_TABLE_VALUE_TYPE_ARRAY: tblite_table_value_type = 5;
pub const TBLITE_TABLE_VALUE_TYPE_TABLE: tblite_table_value_type = 6;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tblite_xtb_config {
    pub smooth_cutoff: c_double,
}
pub type tblite_logger_callback =
    Option<unsafe extern "C" fn(tblite_error, *mut c_char, c_int, *mut c_void)>;
unsafe extern "C" {
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_gfn2_calculator(
        ctx: tblite_context,
        mol: tblite_structure,
        config: *mut tblite_xtb_config,
    ) -> tblite_calculator;
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_gfn1_calculator(
        ctx: tblite_context,
        mol: tblite_structure,
        config: *mut tblite_xtb_config,
    ) -> tblite_calculator;
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_ipea1_calculator(
        ctx: tblite_context,
        mol: tblite_structure,
        config: *mut tblite_xtb_config,
    ) -> tblite_calculator;
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_xtb_calculator(
        ctx: tblite_context,
        mol: tblite_structure,
        param: tblite_param,
        config: *mut tblite_xtb_config,
    ) -> tblite_calculator;
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_delete_calculator(calc: *mut tblite_calculator) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_calculator_accuracy(
        ctx: tblite_context,
        calc: tblite_calculator,
        acc: c_double,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_calculator_max_iter(
        ctx: tblite_context,
        calc: tblite_calculator,
        max_iter: c_int,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_calculator_mixer_damping(
        ctx: tblite_context,
        calc: tblite_calculator,
        damping: c_double,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_calculator_mixer_memory(
        ctx: tblite_context,
        calc: tblite_calculator,
        memory: c_int,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_calculator_mixer(
        ctx: tblite_context,
        calc: tblite_calculator,
        mixer: tblite_mixer,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_calculator_temperature_annealing(
        ctx: tblite_context,
        calc: tblite_calculator,
        initial_etemp: c_double,
        hold: c_int,
        cycles: c_int,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_calculator_guess(
        ctx: tblite_context,
        calc: tblite_calculator,
        guess: tblite_guess,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_calculator_temperature(
        ctx: tblite_context,
        calc: tblite_calculator,
        etemp: c_double,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_calculator_save_integrals(
        ctx: tblite_context,
        calc: tblite_calculator,
        save_integrals: c_int,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_calculator_shell_count(
        ctx: tblite_context,
        calc: tblite_calculator,
        nsh: *mut c_int,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_calculator_shell_map(
        ctx: tblite_context,
        calc: tblite_calculator,
        sh2at: *mut c_int,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_calculator_angular_momenta(
        ctx: tblite_context,
        calc: tblite_calculator,
        am: *mut c_int,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_calculator_orbital_count(
        ctx: tblite_context,
        calc: tblite_calculator,
        nao: *mut c_int,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_calculator_orbital_map(
        ctx: tblite_context,
        calc: tblite_calculator,
        ao2sh: *mut c_int,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_singlepoint(
        ctx: tblite_context,
        mol: tblite_structure,
        calc: tblite_calculator,
        res: tblite_result,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_push_back_post_processing_str(
        ctx: tblite_context,
        calc: tblite_calculator,
        mol: tblite_structure,
        charptr: *mut c_char,
    ) -> ();
    /// C declaration in `calculator.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_push_back_post_processing_param(
        ctx: tblite_context,
        calc: tblite_calculator,
        mol: tblite_structure,
        param: tblite_param,
    ) -> ();
    /// C declaration in `container.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_electric_field(efield: *mut c_double) -> tblite_container;
    /// C declaration in `container.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_spin_polarization(
        ctx: tblite_context,
        mol: tblite_structure,
        calc: tblite_calculator,
        wscale: c_double,
    ) -> tblite_container;
    /// C declaration in `container.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_calculator_push_back(
        ctx: tblite_context,
        calc: tblite_calculator,
        cont: *mut tblite_container,
    ) -> ();
    /// C declaration in `container.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_delete_container(cont: *mut tblite_container) -> ();
    /// C declaration in `context.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_context() -> tblite_context;
    /// C declaration in `context.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_delete_context(ctx: *mut tblite_context) -> ();
    /// C declaration in `context.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_check_context(ctx: tblite_context) -> c_int;
    /// C declaration in `context.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_context_error(
        ctx: tblite_context,
        buffer: *mut c_char,
        buffersize: *const c_int,
    ) -> ();
    /// C declaration in `context.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_context_logger(
        ctx: tblite_context,
        callback: tblite_logger_callback,
        userdata: *mut c_void,
    ) -> ();
    /// C declaration in `context.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_context_color(ctx: tblite_context, color: c_int) -> ();
    /// C declaration in `context.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_context_verbosity(ctx: tblite_context, verbosity: c_int) -> ();
    /// C declaration in `double_dictionary.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_n_entries_dict(error: tblite_error, dict: tblite_double_dictionary) -> c_int;
    /// C declaration in `double_dictionary.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_array_entry_index(
        error: tblite_error,
        dict: tblite_double_dictionary,
        index: *const c_int,
        array: *mut c_double,
    ) -> ();
    /// C declaration in `double_dictionary.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_array_size_index(
        error: tblite_error,
        dict: tblite_double_dictionary,
        index: *const c_int,
        dim1: *mut c_int,
        dim2: *mut c_int,
        dim3: *mut c_int,
    ) -> ();
    /// C declaration in `double_dictionary.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_array_entry_label(
        error: tblite_error,
        dict: tblite_double_dictionary,
        label: *mut c_char,
        array: *mut c_double,
    ) -> ();
    /// C declaration in `double_dictionary.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_array_size_label(
        error: tblite_error,
        dict: tblite_double_dictionary,
        label: *mut c_char,
        dim1: *mut c_int,
        dim2: *mut c_int,
        dim3: *mut c_int,
    ) -> ();
    /// C declaration in `double_dictionary.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_label_entry_index(
        error: tblite_error,
        dict: tblite_double_dictionary,
        index: *const c_int,
        label: *mut c_char,
        buffersize: *const c_int,
    ) -> ();
    /// C declaration in `double_dictionary.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_delete_double_dictionary(dict: *mut tblite_double_dictionary) -> ();
    /// C declaration in `error.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_error() -> tblite_error;
    /// C declaration in `error.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_delete_error(arg0: *mut tblite_error) -> ();
    /// C declaration in `error.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_check_error(arg0: tblite_error) -> c_int;
    /// C declaration in `error.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_clear_error(arg0: tblite_error) -> ();
    /// C declaration in `error.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_error(arg0: tblite_error, arg1: *mut c_char, arg2: *const c_int) -> ();
    /// C declaration in `error.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_set_error(arg0: tblite_error, arg1: *mut c_char, arg2: *const c_int) -> ();
    /// C declaration in `param.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_param() -> tblite_param;
    /// C declaration in `param.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_delete_param(param: *mut tblite_param) -> ();
    /// C declaration in `param.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_load_param(error: tblite_error, param: tblite_param, table: tblite_table) -> ();
    /// C declaration in `param.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_dump_param(error: tblite_error, param: tblite_param, table: tblite_table) -> ();
    /// C declaration in `param.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_export_gfn2_param(error: tblite_error, param: tblite_param) -> ();
    /// C declaration in `param.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_export_gfn1_param(error: tblite_error, param: tblite_param) -> ();
    /// C declaration in `param.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_export_ipea1_param(error: tblite_error, param: tblite_param) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_result() -> tblite_result;
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_copy_result(res: tblite_result) -> tblite_result;
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_delete_result(res: *mut tblite_result) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_number_of_atoms(
        error: tblite_error,
        res: tblite_result,
        nat: *mut c_int,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_number_of_shells(
        error: tblite_error,
        res: tblite_result,
        nsh: *mut c_int,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_number_of_orbitals(
        error: tblite_error,
        res: tblite_result,
        nao: *mut c_int,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_number_of_spins(
        error: tblite_error,
        res: tblite_result,
        nspin: *mut c_int,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_energy(
        error: tblite_error,
        res: tblite_result,
        energy: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_energies(
        error: tblite_error,
        res: tblite_result,
        energies: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_gradient(
        error: tblite_error,
        res: tblite_result,
        gradient: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_virial(
        error: tblite_error,
        res: tblite_result,
        sigma: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_charges(
        error: tblite_error,
        res: tblite_result,
        charges: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_bond_orders(
        error: tblite_error,
        res: tblite_result,
        mbo: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_dipole(
        error: tblite_error,
        res: tblite_result,
        dipole: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_quadrupole(
        error: tblite_error,
        res: tblite_result,
        quadrupole: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_orbital_energies(
        error: tblite_error,
        res: tblite_result,
        emo: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_orbital_occupations(
        error: tblite_error,
        res: tblite_result,
        occ: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_orbital_coefficients(
        error: tblite_error,
        res: tblite_result,
        cmat: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_density_matrix(
        error: tblite_error,
        res: tblite_result,
        pmat: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_overlap_matrix(
        error: tblite_error,
        res: tblite_result,
        smat: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_result_hamiltonian_matrix(
        error: tblite_error,
        res: tblite_result,
        hmat: *mut c_double,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_post_processing_dict(
        error: tblite_error,
        res: tblite_result,
    ) -> tblite_double_dictionary;
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_save_result_wavefunction(
        error: tblite_error,
        res: tblite_result,
        filename: *const c_char,
    ) -> ();
    /// C declaration in `result.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_load_result_wavefunction(
        error: tblite_error,
        res: tblite_result,
        filename: *const c_char,
    ) -> ();
    /// C declaration in `solvation.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_ddx_solvation_epsilon(
        error: tblite_error,
        mol: tblite_structure,
        eps: c_double,
        model: tblite_solvation_param,
    ) -> tblite_container;
    /// C declaration in `solvation.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_ddx_solvation_solvent(
        error: tblite_error,
        mol: tblite_structure,
        solvent: *mut c_char,
        model: tblite_solvation_param,
    ) -> tblite_container;
    /// C declaration in `solvation.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_gb_solvation_epsilon(
        error: tblite_error,
        mol: tblite_structure,
        eps: c_double,
        version: tblite_solvation_param,
        born: tblite_born_kernel,
    ) -> tblite_container;
    /// C declaration in `solvation.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_alpb_solvation_solvent(
        error: tblite_error,
        mol: tblite_structure,
        solvent: *mut c_char,
        version: tblite_solvation_param,
        refstate: tblite_ref_solvation_state,
    ) -> tblite_container;
    /// C declaration in `structure.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_structure(
        error: tblite_error,
        natoms: c_int,
        numbers: *const c_int,
        positions: *const c_double,
        charge: *const c_double,
        uhf: *const c_int,
        lattice: *const c_double,
        periodic: *const bool,
    ) -> tblite_structure;
    /// C declaration in `structure.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_delete_structure(mol: *mut tblite_structure) -> ();
    /// C declaration in `structure.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_update_structure_geometry(
        error: tblite_error,
        mol: tblite_structure,
        positions: *const c_double,
        lattice: *const c_double,
    ) -> ();
    /// C declaration in `structure.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_update_structure_charge(
        error: tblite_error,
        mol: tblite_structure,
        charge: *const c_double,
    ) -> ();
    /// C declaration in `structure.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_update_structure_uhf(
        error: tblite_error,
        mol: tblite_structure,
        uhf: *const c_int,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_table(table: *mut tblite_table) -> tblite_table;
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_delete_table(table: *mut tblite_table) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_set_double(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
        value: *mut c_double,
        n: c_int,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_set_int64_t(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
        value: *mut i64,
        n: c_int,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_set_bool(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
        value: *mut bool,
        n: c_int,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_set_char(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
        value: *mut [c_char; 0],
        n: c_int,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_add_table(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
    ) -> tblite_table;
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_new_array() -> tblite_array;
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_delete_array(array: *mut tblite_array) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_array_push_back_double(
        error: tblite_error,
        array: tblite_array,
        value: c_double,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_array_push_back_int64_t(
        error: tblite_error,
        array: tblite_array,
        value: i64,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_array_push_back_bool(error: tblite_error, array: tblite_array, value: bool)
        -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_array_push_back_char(
        error: tblite_error,
        array: tblite_array,
        value: *mut c_char,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_array_size(error: tblite_error, array: tblite_array) -> c_int;
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_array_get_type(error: tblite_error, array: tblite_array, index: c_int) -> c_int;
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_array_get_double(
        error: tblite_error,
        array: tblite_array,
        index: c_int,
        value: *mut c_double,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_array_get_int64_t(
        error: tblite_error,
        array: tblite_array,
        index: c_int,
        value: *mut i64,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_array_get_bool(
        error: tblite_error,
        array: tblite_array,
        index: c_int,
        value: *mut bool,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_array_get_char(
        error: tblite_error,
        array: tblite_array,
        index: c_int,
        value: *mut c_char,
        n: c_int,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_set_array(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
        array: tblite_array,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_get_type(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
    ) -> c_int;
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_get_bool(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
        value: *mut bool,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_get_int64_t(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
        value: *mut i64,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_get_double(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
        value: *mut c_double,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_get_char(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
        value: *mut c_char,
        n: c_int,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_get_table(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
    ) -> tblite_table;
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_get_array(
        error: tblite_error,
        table: tblite_table,
        key: *mut c_char,
    ) -> tblite_array;
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_get_n_keys(error: tblite_error, table: tblite_table) -> c_int;
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_table_get_key(
        error: tblite_error,
        table: tblite_table,
        index: c_int,
        key: *mut c_char,
        n: c_int,
    ) -> ();
    /// C declaration in `table.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_dump_table(error: tblite_error, table: tblite_table, filename: *mut c_char)
        -> ();
    /// C declaration in `version.h`. See the pinned upstream header for the safety contract.
    pub fn tblite_get_version() -> c_int;
}
