"""Generate bindings for the deliberately small C grammar in the pinned headers.

No network, libclang, or third-party Python packages are needed. Unknown declarations
fail closed. CI checks the output, C ABI sizes, and links every declared symbol.
Run: python tools/generate_bindings.py [--check]
"""
import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENDOR = ROOT / "tblite-sys/vendor/tblite-0.7.0"

def generate():
    headers = sorted((VENDOR / "include/tblite").glob("*.h"))
    assert len(headers) == 12, "Expected the complete pinned header set"
    sources = {p.name: p.read_text() for p in headers}
    clean = {k: re.sub(r"/\*.*?\*/|//[^\n]*", "", v, flags=re.S) for k, v in sources.items()}
    code = "\n".join(clean.values())
    aliases = re.findall(r"typedef\s+struct\s+(_tblite_\w+)\s*\*\s*(tblite_\w+)\s*;", code)
    known = {alias for _, alias in aliases} | {"tblite_xtb_config", "tblite_logger_callback"}
    out = ["// @generated by tools/generate_bindings.py; do not edit.",
           "// Declarations derived from tblite 0.7.0, LGPL-3.0-or-later.",
           "// See vendor/tblite-0.7.0/COPYING{,.LESSER} and NOTICE.md.",
           "use std::ffi::{c_char, c_double, c_int, c_uint, c_void};"]
    for opaque, alias in aliases:
        out += [f"#[repr(C)] pub struct {opaque} {{ _private: [u8; 0] }}", f"pub type {alias} = *mut {opaque};"]
    enums = []
    constants = []
    for match in re.finditer(r"(typedef\s+)?enum\s*(\w+)?\s*\{(.*?)\}\s*(\w+)?\s*;", code, re.S):
        name = match[4] if match[1] else match[2]
        assert name and name.startswith("tblite_"), match[0]
        known.add(name)
        enums.append(name if match[1] else "enum " + name)
        out.append(f"pub type {name} = c_uint;")
        for entry in match[3].split(","):
            if not entry.strip(): continue
            item = re.fullmatch(r"\s*(\w+)\s*=\s*(\d+)\s*", entry)
            assert item, entry
            out.append(f"pub const {item[1]}: {name} = {item[2]};")
            constants.append((item[1], item[2]))
    struct = re.findall(r"typedef\s+struct\s*\{(.*?)\}\s*(\w+)\s*;", code, re.S)
    assert len(struct) == 1 and struct[0][1] == "tblite_xtb_config"
    assert re.fullmatch(r"\s*double\s+smooth_cutoff\s*;\s*", struct[0][0])
    out.append("#[repr(C)] #[derive(Debug, Copy, Clone)] pub struct tblite_xtb_config { pub smooth_cutoff: c_double }")
    cb = re.search(r"typedef\s+void\s*\(\*tblite_logger_callback\)\s*\((.*?)\)\s*;", code, re.S)
    assert cb and re.sub(r"\s+", "", cb[1]) == "tblite_error,char*,int,void*"
    out.append('pub type tblite_logger_callback = Option<unsafe extern "C" fn(tblite_error, *mut c_char, c_int, *mut c_void)>;')
    primitives = {"int": "c_int", "double": "c_double", "char": "c_char", "bool": "bool", "void": "c_void", "int64_t": "i64"}
    def argument(arg, index):
        arg = re.sub(r"\benum\s+", "", arg.strip())
        special = re.fullmatch(r"char\s*\(\*\s*(\w+)\)\s*\[\s*\]", arg)
        if special: return special[1], "*mut [c_char; 0]"
        m = re.fullmatch(r"(const\s+)?(\w+)\s*((?:\*\s*)*)(\w+)?\s*(\[\d*\])?", arg)
        assert m, arg
        const, base, stars, name, arr = m.groups()
        assert base in known or base in primitives, arg
        ty = primitives.get(base, base)
        depth = stars.count("*") + bool(arr)
        for i in range(depth): ty = ("*const " if const and i == 0 else "*mut ") + ty
        if base == "void" and depth == 0: ty = "()"
        name = name or f"arg{index}"
        if name in {"type", "ref", "in", "match"}: name = "r#" + name
        return name, ty
    functions = []
    out.append('unsafe extern "C" {')
    for header, text in clean.items():
        pattern = r"TBLITE_API_(?:ENTRY|CALL)\s+(\w+)\s+TBLITE_API_CALL\s+(tblite_\w+)\s*\((.*?)\)\s*;"
        for m in re.finditer(pattern, text, re.S):
            ret, name, args = m.groups()
            assert ret in known or ret in primitives, m[0]
            argv = [] if args.strip() == "void" else [argument(a, i) for i, a in enumerate(args.split(","))]
            rustret = "()" if ret == "void" else primitives.get(ret, ret)
            out += [f"    /// C declaration in `{header}`. See the pinned upstream header for the safety contract.",
                    f"    pub fn {name}({', '.join(f'{n}: {t}' for n,t in argv)}) -> {rustret};"]
            functions.append({"name": name, "header": header, "return": ret, "arguments": args.strip()})
    out.append("}")
    declared = set(re.findall(r"(?m)^\s*(tblite_\w+)\s*\(", code))
    assert len(functions) == 117 and {f['name'] for f in functions} == declared
    bindings = "\n".join(out) + "\n"
    formatted = subprocess.run(["rustfmt", "--edition", "2021", "--emit", "stdout"], input=bindings, text=True, check=True, capture_output=True).stdout
    probe = ['/* Generated symbol and ABI probe, used only with abi-tests. */', '#include <tblite.h>', '#include <stddef.h>', '#include <stdint.h>',
             '_Static_assert(sizeof(int) == 4, "C int must be 32 bits");', '_Static_assert(sizeof(bool) == 1, "C bool must be 8 bits");',
             '_Static_assert(sizeof(tblite_guess) == 4, "enum ABI");', '_Static_assert(sizeof(tblite_solvation_param) == 4, "enum ABI");' .replace('sizeof(tblite_solvation_param)', 'sizeof(enum tblite_solvation_param)'),
             'size_t tblite_rs_config_size(void) { return sizeof(tblite_xtb_config); }',
             'size_t tblite_rs_config_align(void) { return _Alignof(tblite_xtb_config); }',
             'size_t tblite_rs_link_symbols(void) {', '  volatile uintptr_t symbols[] = {']
    probe += [f'    (uintptr_t)&{f["name"]},' for f in functions]
    probe += ['  };', '  size_t count = 0;', '  for (size_t i=0; i<sizeof(symbols)/sizeof(symbols[0]); ++i) count += symbols[i] != 0;', '  return count;', '}']
    probe += [f'_Static_assert(sizeof({name}) == sizeof(unsigned int), "{name} ABI");' for name in enums]
    probe += [f'_Static_assert({name} == {value}, "{name} value");' for name, value in constants]
    probe += ['_Static_assert(offsetof(tblite_xtb_config, smooth_cutoff) == 0, "config field offset");',
              '_Static_assert(sizeof(double) == 8, "double ABI");',
              '_Static_assert(sizeof(int64_t) == 8, "int64_t ABI");']
    manifest = {"version": "0.7.0", "headers": {k: hashlib.sha256((VENDOR / 'include/tblite' / k).read_bytes()).hexdigest() for k in sources}, "functions": functions}
    return {ROOT / 'tblite-sys/src/bindings.rs': formatted, ROOT / 'tblite-sys/tests/abi.c': '\n'.join(probe)+'\n', ROOT / 'tblite-sys/api.json': json.dumps(manifest, indent=2)+'\n'}

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in generate().items():
        if args.check:
            assert path.read_text() == content, f"Regenerate {path}"
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, newline='\n')
    print('Verified 117 declarations' if args.check else 'Generated 117 declarations')
